# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GHZSwiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GHZSwiftProject
  pod 'SnapKit', '~> 4.2.0'
  pod 'SwiftLint', '0.37.0'

  target 'GHZSwiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GHZSwiftProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
